### ISSUE TITLE
Bug: Committing in OSX breaks since 1.8.1

### ISSUE THREAD

**Issue by avidas** [streamich/git-cz#19]
`npx git-cz` breaks with

```npx: installed 1 in 2.03s
✖  fatal     TypeError: changedFiles is not iterable 
    at getChangedPackages (/Users/avi/.npm/_npx/22780/lib/node_modules/git-cz/dist/cli.js:657:26)
    at Object.exports.createQuestion (/Users/avi/.npm/_npx/22780/lib/node_modules/git-cz/dist/cli.js:470:27)```

**Comment by streamich** [comment]
If you use `1.8.3`, do you still get this error?

```
npm i -g git-cz@latest
```

or 

```
npx git-cz@1.8.3
```

**Comment by avidas** [comment]
Yep ```member-web-storybook git:(avi/mwb-95/events-list-selection-interact) npx git-cz@1.8.3
npx: installed 1 in 1.944s
✖  fatal     TypeError: changedFiles is not iterable 
    at getChangedPackages (/Users/adas/.npm/_npx/39722/lib/node_modules/git-cz/dist/cli.js:657:26)
    at Object.exports.createQuestion (/Users/adas/.npm/_npx/39722/lib/node_modules/git-cz/dist/cli.js:470:27)
    at state.config.questions.map (/Users/adas/.npm/_npx/39722/lib/node_modules/git-cz/dist/cli.js:182:37)
    at Array.map (<anonymous>)
    at createQuestions (/Users/adas/.npm/_npx/39722/lib/node_modules/git-cz/dist/cli.js:181:44)
    at runInteractiveQuestions (/Users/adas/.npm/_npx/39722/lib/node_modules/git-cz/dist/cli.js:586:21)
    at main (/Users/adas/.npm/_npx/39722/lib/node_modules/git-cz/dist/cli.js:120:11)
    at Object.2../createState (/Users/adas/.npm/_npx/39722/lib/node_modules/git-cz/dist/cli.js:158:1)
    at o (/Users/adas/.npm/_npx/39722/lib/node_modules/git-cz/dist/cli.js:1:327)
    at r (/Users/adas/.npm/_npx/39722/lib/node_modules/git-cz/dist/cli.js:1:493)```
